import { Inter, Niconne } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const niconne = Niconne({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-niconne'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${niconne.variable} font-sans`}>
        {children}
      </body>
    </html>
  )
}
